/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CKeyStore */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CKeyStore
#define _Included_xyz_inphinity_sun_security_mscapi_CKeyStore
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CKeyStore_LOCATION_CURRENTUSER
#define xyz_inphinity_sun_security_mscapi_CKeyStore_LOCATION_CURRENTUSER 0L
#undef xyz_inphinity_sun_security_mscapi_CKeyStore_LOCATION_LOCALMACHINE
#define xyz_inphinity_sun_security_mscapi_CKeyStore_LOCATION_LOCALMACHINE 1L
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    loadKeysOrCertificateChains
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_loadKeysOrCertificateChains
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    storeCertificate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BIJJ)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_storeCertificate
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jint, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    removeCertificate
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_removeCertificate
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jint);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    destroyKeyContainer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_destroyKeyContainer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    generateRSAPrivateKeyBlob
 * Signature: (I[B[B[B[B[B[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_generateRSAPrivateKeyBlob
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyStore
 * Method:    storePrivateKey
 * Signature: (Ljava/lang/String;[BLjava/lang/String;I)Lxyz/inphinity/sun/security/mscapi/CPrivateKey;
 */
JNIEXPORT jobject JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyStore_storePrivateKey
  (JNIEnv *, jobject, jstring, jbyteArray, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
