/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CRSACipher */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CRSACipher
#define _Included_xyz_inphinity_sun_security_mscapi_CRSACipher
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_ENCRYPT
#define xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_ENCRYPT 1L
#undef xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_DECRYPT
#define xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_DECRYPT 2L
#undef xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_SIGN
#define xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_SIGN 3L
#undef xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_VERIFY
#define xyz_inphinity_sun_security_mscapi_CRSACipher_MODE_VERIFY 4L
#undef xyz_inphinity_sun_security_mscapi_CRSACipher_PAD_PKCS1_LENGTH
#define xyz_inphinity_sun_security_mscapi_CRSACipher_PAD_PKCS1_LENGTH 11L
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CRSACipher
 * Method:    encryptDecrypt
 * Signature: ([BIJZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CRSACipher_encryptDecrypt
  (JNIEnv *, jclass, jbyteArray, jint, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
