/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey
#define _Included_xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID -1088859394025049194i64
#undef xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID -2289561342425825391i64
#undef xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey_serialVersionUID 12i64
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey
 * Method:    getExponent
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CPublicKey_00024CRSAPublicKey_getExponent
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CPublicKey_CRSAPublicKey
 * Method:    getModulus
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CPublicKey_00024CRSAPublicKey_getModulus
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
