/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CSignature */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CSignature
#define _Included_xyz_inphinity_sun_security_mscapi_CSignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    signCngHash
 * Signature: (I[BIILjava/lang/String;JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_signCngHash
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jstring, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    verifyCngSignedHash
 * Signature: (I[BI[BIILjava/lang/String;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_verifyCngSignedHash
  (JNIEnv *, jclass, jint, jbyteArray, jint, jbyteArray, jint, jint, jstring, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    signHash
 * Signature: (Z[BILjava/lang/String;JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_signHash
  (JNIEnv *, jclass, jboolean, jbyteArray, jint, jstring, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    verifySignedHash
 * Signature: ([BILjava/lang/String;[BIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_verifySignedHash
  (JNIEnv *, jclass, jbyteArray, jint, jstring, jbyteArray, jint, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    importPublicKey
 * Signature: (Ljava/lang/String;[BI)Lxyz/inphinity/sun/security/mscapi/CPublicKey;
 */
JNIEXPORT jobject JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_importPublicKey
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature
 * Method:    importECPublicKey
 * Signature: (Ljava/lang/String;[BI)Lxyz/inphinity/sun/security/mscapi/CPublicKey;
 */
JNIEXPORT jobject JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_importECPublicKey
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
