/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CKey */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CKey
#define _Included_xyz_inphinity_sun_security_mscapi_CKey
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CKey_serialVersionUID -1088859394025049194i64
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKey
 * Method:    cleanUp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_CKey_cleanUp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKey
 * Method:    getContainerName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_inphinity_sun_security_mscapi_CKey_getContainerName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKey
 * Method:    getKeyType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_inphinity_sun_security_mscapi_CKey_getKeyType
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
