/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA
#define _Included_xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA_KEY_SIZE_MIN
#define xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA_KEY_SIZE_MIN 512L
#undef xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA_KEY_SIZE_MAX
#define xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA_KEY_SIZE_MAX 16384L
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_RSA
 * Method:    generateCKeyPair
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Lxyz/inphinity/sun/security/mscapi/CKeyPair;
 */
JNIEXPORT jobject JNICALL Java_xyz_inphinity_sun_security_mscapi_CKeyPairGenerator_00024RSA_generateCKeyPair
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
