/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CSignature_RSA */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CSignature_RSA
#define _Included_xyz_inphinity_sun_security_mscapi_CSignature_RSA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CSignature_RSA
 * Method:    generatePublicKeyBlob
 * Signature: (I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CSignature_00024RSA_generatePublicKeyBlob
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
