/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_PRNG */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_PRNG
#define _Included_xyz_inphinity_sun_security_mscapi_PRNG
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_PRNG_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_PRNG_serialVersionUID -2991854161009191830i64
#undef xyz_inphinity_sun_security_mscapi_PRNG_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_PRNG_serialVersionUID 4129268715132691532i64
/*
 * Class:     xyz_inphinity_sun_security_mscapi_PRNG
 * Method:    generateSeed
 * Signature: (JI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_PRNG_generateSeed
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_PRNG
 * Method:    getContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xyz_inphinity_sun_security_mscapi_PRNG_getContext
  (JNIEnv *, jclass);

/*
 * Class:     xyz_inphinity_sun_security_mscapi_PRNG
 * Method:    releaseContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_inphinity_sun_security_mscapi_PRNG_releaseContext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
