/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_inphinity_sun_security_mscapi_CPublicKey */

#ifndef _Included_xyz_inphinity_sun_security_mscapi_CPublicKey
#define _Included_xyz_inphinity_sun_security_mscapi_CPublicKey
#ifdef __cplusplus
extern "C" {
#endif
#undef xyz_inphinity_sun_security_mscapi_CPublicKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CPublicKey_serialVersionUID -1088859394025049194i64
#undef xyz_inphinity_sun_security_mscapi_CPublicKey_serialVersionUID
#define xyz_inphinity_sun_security_mscapi_CPublicKey_serialVersionUID -2289561342425825391i64
/*
 * Class:     xyz_inphinity_sun_security_mscapi_CPublicKey
 * Method:    getPublicKeyBlob
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xyz_inphinity_sun_security_mscapi_CPublicKey_getPublicKeyBlob
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
